TaskManagement/Areas/Admin/Controllers/CorporateTaskController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TaskManagement.Areas.Admin.Factories;
using TaskManagement.Areas.Admin.Models;
using TaskManagement.Core.Entities;
using TaskManagement.Services.CorporateTasks;
using TaskManagement.Services.Email;

namespace TaskManagement.Areas.Admin.Controllers
{
	[Area("Admin")]

	public class CorporateTaskController : Controller
	{
		#region Fields
		private readonly IEmailService _emailService;
		private readonly ICorporateTaskService _corporateTaskService;
		private readonly IMapper _mapper;
		private readonly ICorporateTaskModelFactory _corporateTaskModelFactory;
		private readonly UserManager<Employee> _userManager;

		#endregion

		#region Ctor
		public CorporateTaskController(IEmailService emailService, ICorporateTaskService corporateTaskService, IMapper mapper, ICorporateTaskModelFactory corporateTaskModelFactory, UserManager<Employee> userManager)
		{
			_corporateTaskService = corporateTaskService;
			_emailService = emailService;
			_mapper = mapper;
			_corporateTaskModelFactory = corporateTaskModelFactory;
			_userManager = userManager;
		}
		#endregion

		#region Methods
		[HttpGet]
		[Authorize(Roles = "Manager,Admin")]
		public async Task<IActionResult> List()
		{
			var models = await _corporateTaskModelFactory.PrepareCorporateTaskModelForListAsync();
			return View(models);
		}
		[HttpGet]
		[Authorize(Roles = "Manager,Admin")]
		public async Task<IActionResult> Create()
		{
			var employees = await _corporateTaskService.GetEmployeesForTaskCreationAsync();
			ViewData["Employees"] = employees;

			return View();
		}



		[HttpPost]
		[Authorize(Roles = "Manager,Admin")]
		public async Task<IActionResult> Create(CorporateTaskModel model)
		{
			if (model == null)
			{
				return BadRequest("Model cannot be null");
			}

			var corporateTask = _mapper.Map<CorporateTask>(model);

			string baseUrl = Url.Action("TaskDetails", "EmployeeTask", null, Request.Scheme);
			await _corporateTaskService.CreateCorporateTaskAsync(corporateTask, model.EmployeeTasks, baseUrl);

			return RedirectToAction("List");
		}



		[HttpPost]
		public async Task<IActionResult> Delete(int id)
		{
			try
			{
				await _corporateTaskService.DeleteCorporateTaskAsync(id);
				return Json(new { success = true });
			}
			catch (Exception ex)
			{
				return Json(new { success = false, message = ex.Message });
			}
		}


		[HttpPost]
		[Authorize(Roles = "Manager,Admin")]
		public async Task<IActionResult> ApproveTask(int id)
		{
			try
			{
				var result = await _corporateTaskService.ApproveTaskAsync(id);
				return Json(new { success = result });
			}
			catch (ArgumentException ex)
			{
				return Json(new { success = false, message = ex.Message });
			}
			catch (KeyNotFoundException ex)
			{
				return Json(new { success = false, message = ex.Message });
			}
			catch (Exception ex)
			{
				// Log the exception (ex) to a logging framework or database if necessary
				return StatusCode(500, new { success = false, message = "Internal server error: " + ex.Message });
			}
		}
		[HttpGet]
		[Authorize(Roles = "Employee,Manager,Admin")]
		public async Task<IActionResult> Details(int id)
		{
			try
			{
				var taskViewModel = await _corporateTaskModelFactory.PrepareCorporateTaskModelForDetailAsync(id);
				return View(taskViewModel);
			}
			catch (KeyNotFoundException)
			{
				return NotFound();
			}
			catch (Exception ex)
			{
				// Log the exception (ex) to a logging framework or database if necessary
				return StatusCode(500, new { success = false, message = "Internal server error: " + ex.Message });
			}
		}







		#endregion

	}
}

TaskManagement/Areas/Admin/Views/CorporateTask/Create.cshtml
@using TaskManagement.Areas.Admin.Models;
@model CorporateTaskModel

@{
    ViewData["Title"] = "Create Task";
    var employees = ViewData["Employees"] as List<SelectListItem>;
    if (employees == null)
    {
        // ViewData["Employees"] null ise veya beklenen türde değilse buraya girebilir
        // Hata işlemleri veya düzeltmeler yapılabilir
    }
}
<div class="container-fluid">
    <div class="row mb-3">
        <div class="col-8">
            <h3>Görev Kayıt</h3>
        </div>
        <div class="col-4 text-end">
            <a asp-action="TaskList" asp-controller="TaskManagement" class="btn btn-outline-dark">Back To List</a>
        </div>
    </div>
    <form asp-action="Create" method="post">
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Detail" class="control-label"></label>
            <textarea asp-for="Detail" class="form-control" rows="3"></textarea>
            <span asp-validation-for="Detail" class="text-danger"></span>
        </div>
        <div class="form-group mt-3">
            <label>Görevin atanacağı çalışan :</label>
            <div class="checkbox-list">
                @foreach (var employee in ViewBag.Employees)
                {
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" name="EmployeeTasks" value="@employee.Value" id="employee_@employee.Value">
                        <label class="form-check-label" for="employee_@employee.Value">@employee.Text</label>
                    </div>
                }
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

TaskManagement/Areas/Admin/Views/CorporateTask/Details.cshtml
@using TaskManagement.Areas.Admin.Models
@model CorporateTaskModel

@{
    ViewData["Title"] = "Task Details";
}

<h1>Task Details</h1>

<div>
    <h4>Task Information</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Model.Name
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Model.StartDate
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Model.EndDate
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Detail)
        </dt>
        <dd class="col-sm-10">
            @Model.Detail
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>
        <dd class="col-sm-10">
            @if (Model.IsApproved)
            {
                <span class="text-success">Onaylandı</span>
            }
            else
            {
                <span class="text-danger">Onaylanmadı</span>
            }
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsInProgress)
        </dt>
        <dd class="col-sm-10">
            @if (Model.IsInProgress)
            {
                <span class="text-success">Evet</span>
            }
            else
            {
                <span class="text-danger">Hayır</span>
            }
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompletionProgress)
        </dt>
        <dd class="col-sm-10">
            @Model.CompletionProgress
        </dd>

        <dt class="col-sm-2">
            Çalışanlar
        </dt>
        <dd class="col-sm-10">
            @string.Join(", ", Model.EmployeeNames.Zip(Model.EmployeeSurnames, (name, surname) => name + " " + surname))
        </dd>
    </dl>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

TaskManagement/Areas/Admin/Views/CorporateTask/List.cshtml
@using System.Security.Claims
@using TaskManagement.Areas.Admin.Models
@model List<CorporateTaskModel>

<link href="https://cdn.datatables.net/2.0.8/css/dataTables.bootstrap5.css" rel="stylesheet" />
<link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />

<h1 class="mb-4">Görev Listesi</h1>
<div class="position-sticky" id="liveAlertPlaceholder"></div>

<table id="dataTable" class="table table-striped mt-4">
    <thead>
        <tr>
            <th>Görev Adı</th>
            <th>Başlangıç Tarihi</th>
            <th>Bitiş Tarihi</th>
            <th>Detaylar</th>
            <th>Yönetici Onayı</th>
            <th>Başlama Durumu</th>
            <th>İlerleme(%)</th>
            @if ((User.HasClaim(x => x.Type == ClaimTypes.Role && x.Value == "Admin")))
            {
                <th>Onay</th>
                <th>Sil</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="CorporateTask" asp-route-id="@item.Id"
                       data-bs-toggle="tooltip" data-bs-placement="top"
                       title="@((item.EmployeeNames != null && item.EmployeeNames.Any()) ? string.Join(", ", item.EmployeeNames) : "No employees assigned")">
                        @item.Name
                    </a>
                </td>
                <td>@item.StartDate</td>
                <td>@item.EndDate</td>
                <td>@item.Detail</td>
                <td class="col-1 isapproved @(item.IsApproved ? "text-success" : "text-danger")">
                    @(item.IsApproved ? "Evet" : "Hayır")
                </td>
                <td class="col-1 @(item.IsInProgress ? "text-success" : "text-danger")">
                    @(item.IsInProgress ? "Evet" : "Hayır")
                </td>
                <td class="col-1">@item.CompletionProgress %</td>
                <td>
                    @if (!item.IsApproved)
                    {
                        if ((User.HasClaim(x => x.Type == ClaimTypes.Role && x.Value == "Admin")))
                        {
                            <button type="button" class="btn btn-sm btn-success btn-approve" data-task-id="@item.Id">İşi Onayla</button>
                        }
                        else
                        {
                            <span class="text-warning">Onaylanmadı</span>
                        }
                    }
                    else
                    {
                        <span class="text-success">Onaylandı</span>
                    }
                </td>
                @if ((User.HasClaim(x => x.Type == ClaimTypes.Role && x.Value == "Admin")))
                {
                    <td><a class="btn btn-danger delete" data-id="@item.Id">Sil</a></td>
                }
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable();

            function showAlert(message, type) {
                const alertPlaceholder = document.getElementById('liveAlertPlaceholder');
                const wrapper = document.createElement('div');
                wrapper.innerHTML = [
                    `<div class="alert alert-${type} alert-dismissible" role="alert">`,
                    `   <div>${message}</div>`,
                    '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                    '</div>'
                ].join('');
                alertPlaceholder.append(wrapper);
            }

            $('.btn-approve').click(function () {
                var taskId = $(this).data('task-id');
                var button = $(this); // Store reference to the clicked button
                var row = button.closest('tr'); // Find the closest row to the clicked button
                var isApprovedCell = row.find('.isapproved'); // Find the isApproved cell in the same row

                $.ajax({
                    url: 'ApproveTask/' + taskId,
                    method: 'POST',
                    success: function (response) {
                        if (response.success) {
                            // Change the button text to "Onaylandı" and disable the button
                            button.replaceWith('<span class="text-success">Onaylandı</span>');
                            // Change the isApproved cell text and class to "Evet" and "text-success"
                            isApprovedCell.text('Evet').removeClass('text-danger').addClass('text-success');
                            showAlert("Görev başarıyla onaylandı.", "success");
                        } else {
                            console.error('Approval failed:', response.message);
                            showAlert("Görev onaylanamadı: " + response.message, "danger");
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error('Error approving task:', error);
                        console.error(xhr.responseText);
                        showAlert("Bir hata oluştu: " + error, "danger");
                    }
                });
            });

            $(document).on('click', '.delete', function () {
                var id = $(this).data('id');
                var row = $(this).closest('tr'); // Find the closest row to the clicked delete button

                if (confirm('Bu kaydı silmek istediğinizden emin misiniz?')) {
                    $.ajax({
                        url: '@Url.Action("Delete", "CorporateTask", new { area = "admin" })',
                        type: 'POST',
                        data: { id: id },
                        success: function (response) {
                            if (response.success) {
                                row.fadeOut(500, function () {
                                    $(this).remove(); // Remove the row from the table after fade out
                                });
                                showAlert("Kayıt başarıyla silindi.", "success");
                            } else {
                                showAlert("Silme işlemi gerçekleştirilemedi: " + response.message, "danger");
                            }
                        },
                        error: function (xhr, status, error) {
                            showAlert("Bir hata oluştu: " + error, "danger");
                        }
                    });
                }
            });

            // Initialize Bootstrap tooltips
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
                return new bootstrap.Tooltip(tooltipTriggerEl)
            })
        });
    </script>
}