TaskManagement/ViewModels/UserViewModel.cs
namespace TaskManagement.Web.ViewModels
{
    public class UserViewModel
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string? Email { get; set;}
        public string? PhoneNumber { get; set; }
        public string? PictureUrl { get; set; }

    }
}

TaskManagement/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TaskManagement.Areas.Admin.Factories;
using TaskManagement.Areas.Admin.Models;
using TaskManagement.Core.Entities;
using TaskManagement.Data;
using TaskManagement.Data.Context;
using TaskManagement.Services.CorporateTasks;
using TaskManagement.Services.Departments;
using TaskManagement.Services.User;
using TaskManagement.Web.Areas.Admin.Models;

namespace TaskManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        #region Props
        
        private readonly AppDbContext _context;
        private readonly UserManager<Employee> _userManager;
        private readonly IUserService _userService;
        private readonly IUserModelFactory _userModelFactory;
        private readonly IDepartmentService _departmentService;
        private readonly IDepartmentModelFactory _departmentModelFactory;
        private readonly ICorporateTaskService _corporateTaskService;
        #endregion

        #region Ctor
        public HomeController(AppDbContext context, UserManager<Employee> userManager,
            IUserService userService,
            IUserModelFactory userModelFactory,
            IDepartmentService departmentService,
            IDepartmentModelFactory departmentModelFactory,ICorporateTaskService corporateTaskService)
        {
            _context = context;
            _userManager = userManager;
            _userService = userService;
            _userModelFactory = userModelFactory;
            _departmentService = departmentService;
            _departmentModelFactory = departmentModelFactory;
            _corporateTaskService = corporateTaskService;
        }
        #endregion

        #region Methods

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // Fetching all users
            var users = await _userService.GetAllUsersAsync();
            var userModelList = await _userModelFactory.PrepareUserModelListAsync(users);

            // Fetching current user's roles
            var currentUser = await _userManager.GetUserAsync(User);
            var userRoles = await _userManager.GetRolesAsync(currentUser);

            // Fetching all corporate tasks
            var corporateTasks = await _corporateTaskService.GetAllCorporateTasksAsync();
            ViewBag.TaskCount = corporateTasks.Where(c=>c.IsFinish == false).Count();
            ViewBag.FinishedTaskCount = corporateTasks.Where(c=>c.IsFinish == true).Count();
            // Fetching all departments
            var departments = await _departmentService.GetAllDepartmentsAsync();
            var selectListItems = _departmentModelFactory.CreateSelectListItems(departments);
            ViewBag.NameSurname = currentUser.Name + " " + currentUser.Surname;
            var taskEmployeeMappings = new Dictionary<int, List<string>>();
            var employeeTasks = _context.EmployeeTasks.ToList();
            foreach (var task in corporateTasks)
            {
                var employeeIds = employeeTasks.Where(et => et.TaskId == task.Id).Select(et => et.EmployeeId).ToList();
                var employeeNames = users.Where(u => employeeIds.Contains(u.Id)).Select(u => $"{u.Name} {u.Surname}").ToList();
                taskEmployeeMappings[task.Id] = employeeNames;
            }

            ViewBag.TaskEmployeeMappings = taskEmployeeMappings;
            // Prepare view model
            var viewModel = new AdminModel()
            {
                Users = users,
                Roles = userRoles.ToList(),
                CorporateTasks = corporateTasks,
                UserModel = userModelList,
                Departments = selectListItems
            };

            // Pass the model to the view
            return View(viewModel);
        }

        #endregion

	}
}

TaskManagement/Areas/Admin/Controllers/RolesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using TaskManagement.Web.Areas.Admin.Models;
using TaskManagement.Core.Entities;
using TaskManagement.Services.User;
using TaskManagement.Services.Role;
using TaskManagement.Areas.Admin.Factories;
using TaskManagement.Areas.Admin.Models;

namespace TaskManagement.Areas.Admin.Controllers
{
	[Authorize(Roles = "Admin")]
	[Area("Admin")]
	public class RolesController : Controller
	{
		#region Fields
		private readonly IRoleService _roleService;
		private readonly RoleManager<AppRole> _roleManager;
		private readonly IMapper _mapper;
		private readonly IUserService _userService;
		private readonly IRoleModelFactory _roleModelFactory;
		#endregion

		#region Ctor
		public RolesController(IRoleService roleService, RoleManager<AppRole> roleManager, IMapper mapper, IUserService userService, IRoleModelFactory roleModelFactory)
		{
			_roleService = roleService;
			_roleManager = roleManager;
			_mapper = mapper;
			_userService = userService;
			_roleModelFactory = roleModelFactory;
		}
		#endregion

		#region Methods
		public async Task<IActionResult> List()
		{
			var roles = await _roleService.GetAllRolesAsync();
			var roleModels = await _roleModelFactory.PrepareRoleModelListAsync(roles); // Await the async method here
			return View(roleModels);
		}
		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create([FromForm] RoleModel model)
		{
			if (ModelState.IsValid)
			{
				var result = await _roleService.CreateRoleAsync(model.Name);

				if (result.Succeeded)
				{
					return Json(new { success = true, role = new { Id = model.Id, Name = model.Name } });
				}
				else
				{
					return Json(new { success = false, message = string.Join(", ", result.Errors.Select(e => e.Description)) });
				}
			}
			return Json(new { success = false, message = "Geçersiz veri." });
		}
		[HttpGet]
		public async Task<IActionResult> Edit(string id)
		{
			var roleToUpdate = await _roleService.GetRoleByIdAsync(id);

			if (roleToUpdate == null)
			{
				throw new Exception("Güncellenecek rol bulunamamıştır.");
			}

			var model = _mapper.Map<RoleModel>(roleToUpdate);


			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(RoleModel request)
		{
			var roleToUpdate = await _roleService.GetRoleByIdAsync(request.Id.ToString());

			if (roleToUpdate == null)
			{
				throw new Exception("Güncellenecek rol bulunamamıştır.");
			}

			roleToUpdate.Name = request.Name;

			var updateResult = await _roleService.UpdateRoleAsync(roleToUpdate);

			if (!updateResult.Succeeded)
			{
				throw new Exception("Rol güncelleme işlemi başarısız: " + string.Join(", ", updateResult.Errors.Select(e => e.Description)));
			}

			ViewData["SuccessMessage"] = "Rol bilgisi güncellenmiştir";

			return View();
		}

		public async Task<IActionResult> Delete(string id)
		{
			var deleteResult = await _roleService.DeleteRoleAsync(id);

			TempData["SuccessMessage"] = "Rol silinmiştir.";

			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public async Task<IActionResult> AssignRoleToUser(string id)
		{
			var currentUser = await _userService.GetUserByIdAsync(id);
			if (currentUser == null)
			{
				return NotFound();
			}

			ViewBag.userId = id;

			try
			{
				var roles = await _roleService.GetAllRolesAsync();
				var userRoles = await _roleService.GetUserRolesAsync(currentUser);

				var roleModelList = _mapper.Map<List<RoleModel>>(roles);

				foreach (var role in roleModelList)
				{
					role.Exist = userRoles.Contains(role.Name);
				}

				return View(roleModelList);
			}
			catch (Exception ex)
			{
				// Handle exception or log it
				return StatusCode(500, $"Internal server error: {ex.Message}");
			}
		}

		[HttpPost]
		public async Task<IActionResult> AssignRoleToUser(string userId, List<RoleModel> requestList)
		{
			var userToAssignRoles = await _userService.GetUserByIdAsync(userId);
			if (userToAssignRoles == null)
			{
				return NotFound();
			}

			foreach (var role in requestList)
			{
				if (role.Exist)
				{
					await _roleService.AddUserToRoleAsync(userToAssignRoles, role.Name);
				}
				else
				{
					await _roleService.RemoveUserFromRoleAsync(userToAssignRoles, role.Name);
				}
			}

			return RedirectToAction(nameof(RolesController.List), "List");
		}


		#endregion
	}
}

TaskManagement/Areas/Admin/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskManagement.Areas.Admin.Factories;
using TaskManagement.Areas.Admin.Models;
using TaskManagement.Core.Entities;
using TaskManagement.Services.Departments;
using TaskManagement.Services.User;
using TaskManagement.Web.Areas.Admin.Models;

namespace TaskManagement.Areas.Admin.Controllers
{
	[Area("Admin")]

	public class UserController : Controller
	{
		#region Props

		private readonly UserManager<Employee> _userManager;
		private readonly IUserService _userService;
		private readonly IMapper _mapper;
		private readonly IDepartmentService _departmentService;
		private readonly IDepartmentModelFactory _departmentModelFactory;
		private readonly IUserModelFactory _userModelFactory;
		private readonly IHttpContextAccessor _httpContextAccessor;

		#endregion

		#region Ctor 

		public UserController(UserManager<Employee> userManager,IHttpContextAccessor httpContextAccessor, IUserService userService, IMapper mapper, IDepartmentService departmentService, IDepartmentModelFactory departmentModelFactory, IUserModelFactory userModelFactory)
		{
			_userManager = userManager;
			_userService = userService;
			_mapper = mapper;
			_departmentService = departmentService;
			_departmentModelFactory = departmentModelFactory;
			_userModelFactory = userModelFactory;
			_httpContextAccessor = httpContextAccessor;
		}

		#endregion

		#region Methods
		[HttpGet]
		public async Task<IActionResult> List()
		{
			// Fetching all users
			var users = await _userService.GetAllUsersAsync();
			var userModelList = await _userModelFactory.PrepareUserModelListAsync(users);

			// Fetching the current user
			var currentUser = await _userManager.GetUserAsync(User);

			ViewBag.NameSurname = currentUser.Name + " " + currentUser.Surname;

			// Fetching all departments
			var departments = await _departmentService.GetAllDepartmentsAsync();
			var selectListItems = _departmentModelFactory.CreateSelectListItems(departments);

			var viewModel = new UserListAndCreateModel()
			{
				UserModel = userModelList ?? new List<UserModel>(), // Ensure UserModel is not null
				CreateUserViewModel = new CreateUserViewModel(),
				Departments = selectListItems ?? new List<SelectListItem>(), // Ensure Departments is not null
			};

			return View(viewModel);
		}

		[HttpGet]
		public async Task<IActionResult> Create()
		{
			var departments = await _departmentService.GetAllDepartmentsAsync();
			var selectListItems = _departmentModelFactory.CreateSelectListItems(departments);

			var model = new SignUpViewModel
			{
				Departments = selectListItems
			};

			return View(model);
		}
		[HttpPost]
		public async Task<IActionResult> Create(CreateUserViewModel request)
		{
			var departments = await _departmentService.GetAllDepartmentsAsync();
			request.Departments = _departmentModelFactory.CreateSelectListItems(departments);

			var department = await _departmentService.GetDepartmentByIdAsync(request.DepartmentId);

			var user = _mapper.Map<Employee>(request);
			user.UserName = user.Email;
			var identityResult = await _userService.CreateUserAsync(user, request.Password);

			if (identityResult.Succeeded)
			{
				TempData["SuccessMessage"] = "Üyelik kayıt işlemi başarı ile gerçekleşmiştir";
				return RedirectToAction(nameof(Create));
			}

			request.Errors = identityResult.Errors.Select(x => x.Description).ToList();
			return View(request);
		}


		public async Task<IActionResult> DeleteUser(string id)
		{
			try
			{
				var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id.ToString() == id);
				if (user != null)
				{
					user.IsDeleted = true;
					await _userManager.UpdateAsync(user);
					return Json(new { success = true });
				}
				else
				{
					return Json(new { success = false, message = "Kullanıcı bulunamadı." });
				}
			}
			catch (Exception ex)
			{
				return Json(new { success = false, message = ex.Message });
			}
		}
        [HttpPost]
        public async Task<IActionResult> CreateAjax(CreateUserViewModel request)
        {
            var departments = await _departmentService.GetAllDepartmentsAsync();
            request.Departments = _departmentModelFactory.CreateSelectListItems(departments);

            var department = await _departmentService.GetDepartmentByIdAsync(request.DepartmentId);

            var user = _mapper.Map<Employee>(request);
            user.UserName = user.Email;
            var identityResult = await _userService.CreateUserAsync(user, request.Password);

            if (identityResult.Succeeded)
            {
                return Json(new { success = true, message = "User created successfully." });
            }

            return Json(new { success = false, message = string.Join(", ", identityResult.Errors.Select(e => e.Description)) });
        }
        #endregion
    }
}

TaskManagement/Areas/Admin/Views/Home/Create.cshtml
@model SignUpViewModel
@section Scripts
{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2>Kullanıcı Kayıt Formu</h2>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-info" role="alert">
                @TempData["SuccessMessage"]
            </div>
        }

        <div asp-validation-summary="ModelOnly" class="alert alert-danger" role="alert">
        </div>

        <form asp-controller="Home" asp-action="SignUp" method="post">
            <div class="row mb-3 mt-4">
                <label for="Name" class="col-md-4 col-form-label" asp-for="Name"></label>
                <div class="col-md-8">
                    <input asp-for="Name" class="form-control">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="Surname" class="col-md-4 col-form-label" asp-for="Surname"></label>
                <div class="col-md-8">
                    <input asp-for="Surname" class="form-control">
                    <span class="text-danger" asp-validation-for="Surname"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="Email" class="col-md-4 col-form-label" asp-for="Email"></label>
                <div class="col-md-8">
                    <input asp-for="Email" class="form-control">
                    <span class="text-danger" asp-validation-for="Email"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="Phone" class="col-md-4 col-form-label" asp-for="Phone"></label>
                <div class="col-md-8">
                    <input asp-for="Phone" class="form-control">
                    <span class="text-danger" asp-validation-for="Phone"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="DepartmentId" class="col-md-4 col-form-label" asp-for="DepartmentId"></label>
                <div class="col-md-8">
                    <select asp-for="DepartmentId" class="form-control" asp-items="Model.Departments">
                        <option value="">Bir departman seçiniz</option>
                    </select>
                    <span class="text-danger" asp-validation-for="DepartmentId"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="Password" class="col-md-4 col-form-label" asp-for="Password"></label>
                <div class="col-md-8">
                    <input asp-for="Password" class="form-control">
                    <span class="text-danger" asp-validation-for="Password"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="PasswordConfirm" class="col-md-4 col-form-label" asp-for="PasswordConfirm"></label>
                <div class="col-md-8">
                    <input asp-for="PasswordConfirm" class="form-control">
                    <span class="text-danger" asp-validation-for="PasswordConfirm"></span>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-8 offset-md-4">
                    <button type="submit" class="btn btn-primary">Kayıt Ol</button>
                </div>
            </div>
        </form>
    </div>
</div>

TaskManagement/Areas/Admin/Views/Home/_Chart.cshtml
@using TaskManagement.Models
@model CorporateTaskModel
<!--begin::Chart widget 4-->
<div class="card card-flush overflow-hidden h-md-100">
    <!--begin::Header-->
    <div class="card-header py-5">
        <!--begin::Title-->
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label fw-bold text-dark">Görevler Tablosu</span>
        </h3>
        <!--end::Title-->
    </div>
    <!--end::Header-->
    <!--begin::Card body-->
    <div style="height: 400px;" id="chartdiv"></div>
    <!--end::Card body-->
</div>
<!--end::Chart widget 4-->

TaskManagement/Areas/Admin/Views/Home/_FinishedTasks.cshtml
@model TaskManagement.Areas.Admin.Models.AdminModel
@{
var taskEmployeeMappings = ViewBag.TaskEmployeeMappings as Dictionary<int, List<string>>;
}
<!--begin::Table Widget 5-->
<div class="card card-flush h-xl-100">
	<!--begin::Card header-->
	<div class="card-header pt-7">
		<!--begin::Title-->
		<h3 class="card-title align-items-start flex-column">
			<span class="card-label fw-bold text-dark">Bitirilen Görev Listesi</span>
			<span class="text-gray-400 mt-1 fw-semibold fs-6">Bitirilen görev sayısı @ViewBag.FinishedTaskCount</span>
		</h3>
		<!--end::Title-->
	</div>
	<!--end::Card header-->
	<div class="card-body pt-6">
		<!--begin::Table container-->
		<div class="table-responsive">
			<!--begin::Table-->
			<table class="table table-row-dashed align-middle gs-0 gy-3 my-0">
				<!--begin::Table head-->
				<thead>
				<tr class="fs-7 fw-bold text-gray-400 border-bottom-0">
					<th class="p-0 pb-3 min-w-175px text-start">Görev Adı</th>
					<th class="p-0 pb-3 min-w-100px text-center">Proje Durumu</th>
					<th class="p-0 pb-3 min-w-175px text-center pe-5">Başlangıç Tarihi</th>
					<th class="p-0 pb-3 w-175px text-center pe-5">Bitiş Tarihi</th>
					<th class="p-0 pb-3 w-50px text-end">Detaylar</th>
				</tr>
				</thead>
				<!--end::Table head-->
				<!--begin::Table body-->
				<tbody>
				@foreach (var task in Model.CorporateTasks.Where(t => t.IsFinish == true))
				{
				<tr>
					<td>
						<div class="d-flex align-items-center">
							<div class="symbol symbol-50px me-3">
								<img src="/assets/media/stock/600x600/img-49.jpg" class="" alt=""/>
							</div>
							<div class="d-flex justify-content-start flex-column">
								<a href="#" class="text-gray-800 fw-bold text-hover-primary mb-1 fs-6">@task.Name</a>
								@if (taskEmployeeMappings != null && taskEmployeeMappings.ContainsKey(task.Id))
								{
								foreach (var employee in taskEmployeeMappings[task.Id])
								{
								<span class="text-gray-400 fw-semibold d-block fs-7">@employee</span>
								}
								}
							</div>
						</div>
					</td>
					<td class="text-center pe-5">
						@if (task.IsFinish ==true)
						{
						<span class="badge py-3 px-4 fs-7 badge-light-success">Bitirildi</span>
						}
						else
						{
							<span class="badge py-3 px-4 fs-7 badge-light-danger">Bitirildi</span>
						}
					</td>
					<td class="text-center pe-5">
						<span class="text-gray-600 fw-bold fs-6">@task.StartDate</span>
					</td>
					<td class="text-center pe-5">
						<span class="text-gray-600 fw-bold fs-6">@task.EndDate</span>
					</td>
					<td class="text-end">
						<a asp-action="Details" asp-controller="CorporateTask" asp-route-id="@task.Id" class="btn btn-sm btn-icon btn-bg-light btn-active-color-primary w-30px h-30px">
							<i class="ki-duotone ki-black-right fs-2 text-gray-500"></i>
						</a>
					</td>
				</tr>
				}
				</tbody>
				<!--end::Table body-->
			</table>
		</div>
		<!--end::Table-->
	</div>
</div>
<!--end::Table Widget 5-->

TaskManagement/Areas/Admin/Views/Home/_Users.cshtml
@using TaskManagement.Models
@model TaskManagement.Areas.Admin.Models.AdminModel
<!--begin::Col-->
<div class="col-xl-12">
	<!--begin::Table widget 14-->
	<div class="card card-flush h-md-100">
		<!--begin::Header-->
		<div class="card-header pt-2">
			<!--begin::Title-->
			<h3 class="card-title align-items-start flex-column">
				<span class="card-label fw-bold text-gray-800">Kullanıcı Listesi</span>
			</h3>
			<!--end::Title-->
		</div>
		<!--end::Header-->
		<!--begin::Body-->
		<div class="card-body pt-3">
			<!--begin::Table container-->
			<div class="table-responsive">
				<!--begin::Table-->
				<!--begin::Table-->
				<table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_table_users">
					<thead>
					<tr class="text-start text-muted fw-bold fs-7 text-uppercase gs-0">
						<th class="min-w-125px">Çalışan</th>
						<th class="min-w-125px">Departman</th>
						<th class="min-w-125px">Son giriş tarihi</th>
						<th class="min-w-125px">Rol</th>
						<th class="text-end min-w-100px">İşlemler</th>
					</tr>
					</thead>
					<tbody class="text-gray-600 fw-semibold">
					@foreach (var user in Model.UserModel)
					{
					<tr>
						<td class="d-flex align-items-center">
							<!--begin:: Avatar -->
							<div class="symbol symbol-circle symbol-50px overflow-hidden me-3">
								<a href="#">
									<div class="symbol-label">
										<img src="assets/media/avatars/300-6.jpg" alt="@user.Name @user.Surname" class="w-100" />
									</div>
								</a>
							</div>
							<!--end::Avatar-->
							<!--begin::User details-->
							<div class="d-flex flex-column">
								<a href="#" class="text-gray-800 text-hover-primary mb-1">@user.Name @user.Surname</a>
								<span>@user.Email</span>
							</div>
							<!--begin::User details-->
						</td>
						<td>@user.DepartmentName</td>
						<td>
							<div class="badge badge-light fw-bold">@user.LastLoginDate</div>
						</td>
						<td>
							@{
							var rolesDisplay = user.Roles.Select(role => role == "Manager" ? "Yönetici" : (role == "Employee" ? "Çalışan" : role));
							@string.Join(", ", rolesDisplay)
							}
						</td>

						@if (User.IsInRole("Admin"))
						{
						<td class="text-end">
							<a href="#" class="btn btn-light btn-active-light-primary btn-flex btn-center btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
								İşlemler
								<i class="ki-duotone ki-down fs-5 ms-1"></i>
							</a>
							<!--begin::Menu-->
							<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true">
								<!--begin::Menu item-->
								<div class="menu-item px-3">
									<a asp-controller="Roles" asp-action="AssignRoleToUser" class="menu-link px-3">Rol Ata</a>
								</div>
								<!--end::Menu item-->
								<!--begin::Menu item-->
								<div class="menu-item px-3">
									<a asp-controller="User" asp-action="Delete" class="menu-link px-3" data-kt-users-table-filter="delete_row">Delete</a>
								</div>
								<!--end::Menu item-->
							</div>
							<!--end::Menu-->
						</td>
						}else{
						<td class="text-end">
							<a href="#" class="btn btn-light btn-active-light-primary btn-flex btn-center btn-sm" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
								İşlemler
								<i class="ki-duotone ki-down fs-5 ms-1"></i>
							</a>
							<!--begin::Menu-->
							<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true">
								<!--begin::Menu item-->
								<div class="menu-item px-3">
									<a href="#" disabled class="menu-link px-3">Rol Ata</a>
								</div>
								<!--end::Menu item-->
								<!--begin::Menu item-->
								<div class="menu-item px-3">
									<a asp-controller="User" asp-action="Delete" disabled class="menu-link px-3" data-kt-users-table-filter="delete_row">Sil</a>
								</div>
								<!--end::Menu item-->
							</div>
							<!--end::Menu-->
						</td>
						}

					</tr>
					}
					</tbody>
				</table>
				<!--end::Table-->
			</div>
			<!--end::Table-->
		</div>
		<!--end: Card Body-->
	</div>
	<!--end::Table widget 14-->
</div>
<!--begin::Col-->